### ISSUE TITLE
GUI not working on windows 10

### ISSUE THREAD

**Issue by Vinay-Gajjar** [ghazi19033/mit-control-system#1]
Hi @ghazi19033, I am trying to run this program on windows 10 and for some reason the com port is not showing up on the GUI is there a way to bypass this issue?

**Comment by Vinay-Gajjar** [comment]
@ghazi19033

**Comment by ghazi19033** [comment]
Hey,
After a month of research I finally found the fault. There is a problem
with the library. I will forward you a set of commands in a few hours

**Comment by Vinay-Gajjar** [comment]
Okay Thanks in advance!. Struggled for a week trying to debug.

**Comment by ghazi19033** [comment]
Hey
Run these command independently on power shell. I hope this helps you to
complete the course.

pip install --upgrade python-socketio==4.6.0

pip install --upgrade python-engineio==3.13.2

pip install --upgrade Flask-SocketIO==4.3.1

**Comment by Vinay-Gajjar** [comment]
python server.py
async_mode is eventlet
<Semaphore c=1 _w[0]>
 * Restarting with stat
async_mode is eventlet
<Semaphore c=1 _w[0]>
 * Debugger is active!
 * Debugger PIN: 967-727-487
(11996) wsgi starting up on http://127.0.0.1:8090
(11996) accepted ('127.0.0.1', 51237)
(11996) accepted ('127.0.0.1', 58927)
A user connected
Starting serial background thread.
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET / HTTP/1.1" 200 18723 0.009973
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/jquery-ui.min.css HTTP/1.1" 304 205 0.003990
(11996) accepted ('127.0.0.1', 58616)
(11996) accepted ('127.0.0.1', 63694)
(11996) accepted ('127.0.0.1', 52082)
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/bootstrap.min.css HTTP/1.1" 304 205 0.002994
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/jquery.mobile-1.4.5.min.css HTTP/1.1" 304 215 0.001993
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/gui_style.css HTTP/1.1" 304 201 0.002993
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/socket.io.js HTTP/1.1" 304 200 0.001993
(11996) accepted ('127.0.0.1', 56051)
(11996) accepted ('127.0.0.1', 54845)
(11996) accepted ('127.0.0.1', 50528)
(11996) accepted ('127.0.0.1', 62035)
(11996) accepted ('127.0.0.1', 60706)
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/d3.min.js HTTP/1.1" 304 197 0.001996
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/jquery.js HTTP/1.1" 304 197 0.000997
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/jquery-ui.min.js HTTP/1.1" 304 204 0.002994
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/bootstrap.min.js HTTP/1.1" 304 204 0.000996
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/jquery.mobile-1.4.5.min.js HTTP/1.1" 304 214 0.000997
(11996) accepted ('127.0.0.1', 64619)
(11996) accepted ('127.0.0.1', 62560)
127.0.0.1 - - [24/Jul/2021 16:10:55] "GET /static/images/ajax-loader.gif HTTP/1.1" 404 380 0.000997

**Comment by Vinay-Gajjar** [comment]
Hey I tried adding the code using power shell everything updated to the correct version, but the com port box is still blank. You think there maybe another command or possibly the python version that is affecting this. Tried to disconnect and reconnect the Arduino too, but that didn't work.

**Comment by Vinay-Gajjar** [comment]
async_mode is eventlet
<Semaphore c=1 _w[0]>
----------------------------------------
Unhandled exception in user code execution server!'
Thread: Dummy-1
IDLE Client Address: ('127.0.0.1', 61413)
Request: <socket.socket fd=700, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 61415), raddr=('127.0.0.1', 61413)>




// This is the error i get when i try run the python code through the ide
Thanks

**Comment by Vinay-Gajjar** [comment]
@ghazi19033 sorry for the bombardment of messages. But this has been really tough to do the course and not be able to test anything.
Any help would be grealty appreciated.

**Comment by ghazi19033** [comment]
Sorry, got busy with some work. Could try by retrying everything with a
fresh unzipped code file. Please let me know

**Comment by Vinay-Gajjar** [comment]
@ghazi19033 I tried everything from scratch same issue. Im using python 3.9.6 and windows 10. Maybe that's where the issue is.
Thanks in advance

**Comment by Vinay-Gajjar** [comment]
@ghazi19033 I was able to solve the issue with the help of another person. Thanks so much for all your help.

**Comment by ghazi19033** [comment]
That's great. What was the problem?

**Comment by Vinay-Gajjar** [comment]
Yes so its basically a versioning issue, which was fixed by removing the local host address in the html file, plus updating the requirements.txt file. This user has the updated code if you want to have a look- hajakuja.


Thanks again.
